version: '3'
services:
  leafy-postgres:
    # build: ./leafy-postgresql #제거
    # image: leafy-postgres:5.0.0-compose # 도커허브계정이름/postgres 이름:tag
    image: lunghyun/leafy-postgres:41e8d0d1eeb73e1b2ff2372fdc1746e8e1f6df00
    volumes:
      - mydata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    restart: always

  leafy-backend:
    build: ./leafy-backend
    image: leafy-backend:5.0.0-compose
    environment:
      - DB_URL=leafy-postgres
    depends_on: # 해당 컨테이너가 실행되기 전까지 기다림
      - leafy-postgres
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
    restart: on-failure
      
  leafy-front:
    # build: ./leafy-frontend # 제거
    image: lunghyun/leafy-frontend:30ecd086b7d000225d837f6f85680cdfe634df55
    environment:
      - BACKEND_HOST=leafy-backend
    ports:
      - 80:80
    depends_on:
      - leafy-backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
    restart: on-failure

volumes:
  mydata: